version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "VANILLA"
      OVERRIDE_SERVER_PROPERTIES: "false"
      VERSION: "1.19.3"
      MEMORY: "2G"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraftdata:/data
      - ./plugins:/plugins
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
