version: "3.8"
# docker volume create --name minecraftdata 
services:
  mc:
    image: itzg/minecraft-server
    container_name: vg-mc
    environment:
      OVERRIDE_SERVER_PROPERTIES: "false"
      EULA: "true"
      TYPE: "VANILLA"
      VERSION: "1.19.3"
      MEMORY: "2G"
    ports:
      - "25565:25565"
    volumes:
      - minecraftdata:/data
      - ./plugins:/plugins
      - ./minecraftdata/server.properties:/data/server.properties
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true
